import Link from "next/link";
import { Logo } from "@/components/Logo";

export const metadata = { title: "Privacy Policy · Bid Ledger" };

export default function PrivacyPage() {
  return (
    <div className="min-h-screen w-full bg-paper">
      <div className="mx-auto max-w-3xl px-4 py-10 sm:px-8">
        <Logo />

        <DraftNotice />

        <h1 className="mb-1 mt-8 font-serif text-3xl text-ink">Privacy Policy</h1>
        <p className="mb-8 text-sm text-ink-soft">Last updated: [DATE]</p>

        <div className="space-y-6 text-sm leading-relaxed text-ink">
          <Section title="1. What we collect">
            <p className="mb-2">Bid Ledger collects only what&rsquo;s needed to run the Service:</p>
            <ul className="ml-5 list-disc space-y-1">
              <li>
                <strong>Account data</strong> — name and email for anyone who creates an account or is invited as a
                board member.
              </li>
              <li>
                <strong>Organization data</strong> — whatever a board admin enters: project and bid details, reserve
                fund figures, dues records, and unit/owner information.
              </li>
              <li>
                <strong>Resident and contractor contact info</strong> — name, email, and (for contractors) phone
                number, entered by a board admin to send them their access link.
              </li>
              <li>
                <strong>Photos</strong> a contractor uploads with a weekly project update.
              </li>
              <li>
                <strong>Basic technical data</strong> — the session cookie that keeps you logged in, and standard
                web server logs (IP address, browser type) generated by our hosting provider.
              </li>
            </ul>
          </Section>

          <Section title="2. How we use it">
            <p>
              We use this data solely to operate the Service: showing your Organization&rsquo;s data back to its own
              members, sending transactional email (check-in invitations, contractor/resident access links, password
              resets), and maintaining the security and reliability of the Service. We do not sell personal
              information, and we do not use it for advertising.
            </p>
          </Section>

          <Section title="3. Who we share it with">
            <p className="mb-2">
              We use a small number of subprocessors to run the Service. Each only sees the data it needs to
              perform its function:
            </p>
            <ul className="ml-5 list-disc space-y-1">
              <li><strong>Supabase</strong> — database, authentication, and file storage (contractor photos).</li>
              <li><strong>Resend</strong> — delivery of transactional email (invitations, check-ins, reminders).</li>
              <li><strong>Vercel</strong> — application hosting.</li>
            </ul>
            <p className="mt-2">
              We don&rsquo;t share your Organization&rsquo;s data with any other third party except as required by
              law, or with your consent.
            </p>
          </Section>

          <Section title="4. Data retention">
            <p>
              We retain your Organization&rsquo;s data for as long as the Organization&rsquo;s account is active. If
              a board admin deletes the Organization or requests deletion, we&rsquo;ll remove the data within a
              reasonable period, except where we&rsquo;re required to retain it by law.
            </p>
          </Section>

          <Section title="5. Security">
            <p>
              We use industry-standard practices — encrypted connections, access controls scoped so one
              Organization can never see another&rsquo;s data (row-level security at the database layer), and
              service-role credentials kept server-side only. No system is perfectly secure, and we can&rsquo;t
              guarantee absolute security.
            </p>
          </Section>

          <Section title="6. Children's privacy">
            <p>The Service is intended for adults acting on behalf of a community association board, not children.</p>
          </Section>

          <Section title="7. Your rights">
            <p>
              You can ask us to access, correct, or delete your personal information by contacting{" "}
              <Placeholder>privacy@yourdomain.com</Placeholder>. If you&rsquo;re a resident or contractor who received an
              access link from a board admin and want your information removed, you can also contact your board
              directly — they control that data.
            </p>
          </Section>

          <Section title="8. Changes to this Policy">
            <p>
              We may update this Policy from time to time. If we make material changes, we&rsquo;ll notify board
              admins by email before they take effect. See also our{" "}
              <Link href="/terms" className="text-ink underline hover:text-gold-text">
                Terms of Service
              </Link>
              .
            </p>
          </Section>

          <Section title="9. Contact">
            <p>
              Questions about this Policy: <Placeholder>privacy@yourdomain.com</Placeholder>
            </p>
          </Section>
        </div>
      </div>
    </div>
  );
}

function DraftNotice() {
  return (
    <div className="mt-6 rounded border border-dashed border-gold bg-gold-tint p-3 text-xs text-ink">
      <strong>Draft — not yet finalized.</strong> Bracketed placeholders (like{" "}
      <Placeholder>privacy@yourdomain.com</Placeholder>) need real values, and this document has not been reviewed
      by a lawyer. Replace the placeholders and get it reviewed before relying on it for a real Organization&rsquo;s
      data.
    </div>
  );
}

function Placeholder({ children }: { children: React.ReactNode }) {
  return <span className="font-mono text-gold-text">[{children}]</span>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div>
      <h2 className="mb-2 font-serif text-lg font-semibold text-ink">{title}</h2>
      {children}
    </div>
  );
}
